### ISSUE TITLE
make local version

### ISSUE THREAD

**Issue by kingmanzhang** [obophenotype/human-phenotype-ontology#4735]
@matentzn Hi Nico, how to run the make file now? It seems I have error when running make under src/ontology
```
hp.Makefile:70: warning: overriding commands for target `test'
Makefile:46: warning: ignoring old commands for target `test'
hp.Makefile:74: warning: overriding commands for target `hp.owl'
Makefile:169: warning: ignoring old commands for target `hp.owl'
java.lang.IllegalArgumentException: inputOntology must be specified
	at org.obolibrary.robot.CommandLineHelper.getInputOntology(CommandLineHelper.java:296)
	at org.obolibrary.robot.CommandLineHelper.updateInputOntology(CommandLineHelper.java:351)
	at org.obolibrary.robot.CommandLineHelper.updateInputOntology(CommandLineHelper.java:316)
	at org.obolibrary.robot.ConvertCommand.execute(ConvertCommand.java:128)
	at org.obolibrary.robot.CommandManager.executeCommand(CommandManager.java:242)
	at org.obolibrary.robot.CommandManager.execute(CommandManager.java:177)
	at org.obolibrary.robot.CommandManager.main(CommandManager.java:135)
	at org.obolibrary.robot.CommandLineInterface.main(CommandLineInterface.java:56)
java.lang.IllegalArgumentException: A valid input ontology must be specified
	at org.obolibrary.robot.CommandLineHelper.updateInputOntology(CommandLineHelper.java:355)
	at org.obolibrary.robot.CommandLineHelper.updateInputOntology(CommandLineHelper.java:316)
	at org.obolibrary.robot.ConvertCommand.execute(ConvertCommand.java:128)
	at org.obolibrary.robot.CommandManager.executeCommand(CommandManager.java:242)
	at org.obolibrary.robot.CommandManager.execute(CommandManager.java:177)
	at org.obolibrary.robot.CommandManager.main(CommandManager.java:135)
	at org.obolibrary.robot.CommandLineInterface.main(CommandLineInterface.java:56)
```
Am I missing anything?

**Comment by cmungall** [comment]
I'm not sure why there is Makefile and hp.Makefile, are there instructions on which one should be used when?

**Comment by cmungall** [comment]
I note there is also two copies of README-editors, one txt and one md. We need to consolidate on one

**Comment by kingmanzhang** [comment]
There is also a Makefile-loinc2hpo, a run.sh. I am not sure what I should use.

**Comment by matentzn** [comment]
You cant run hp.Makefile in isolation! 

the correct way to run everything is

```
cd src/ontology
sh run.sh make prepare_release
```

Let me know if you have problems with that!

**Comment by matentzn** [comment]
@cmungall 

Makefile is the main makefile, which is generated by the ODK and should be overwritten during during a repo update to a newer ODK version.

hp.Makefile contains all the custom code of HP, either overwrites of existing goals or new ones that are not by default in the ODK.

**Comment by kingmanzhang** [comment]
Thanks @matentzn 

After installing docker, I was able to run until encountering "error 137". What is that? 

Here is the stack trace:
```
Unable to find image 'obolibrary/odkfull:latest' locally
latest: Pulling from obolibrary/odkfull
8e402f1a9c57: Pull complete 
4866c822999c: Pull complete 
205f26e90552: Pull complete 
e6781c3c63a4: Pull complete 
b65dc89a5f73: Pull complete 
3300ba54eb88: Pull complete 
ae55db30d9ec: Pull complete 
1acafc29775d: Pull complete 
a0c37fc3426c: Pull complete 
0191cbe2eae7: Pull complete 
b0c6431f5834: Pull complete 
0d70e2652bd3: Pull complete 
1a9bfac21154: Pull complete 
93c3d168e014: Pull complete 
7ef87d1211e1: Pull complete 
11ec43d58c10: Pull complete 
cebac32c3e5e: Pull complete 
Digest: sha256:40071fc54c5a410f4fed5455475365d12cba6f31c7b430660e649e1bdceaa448
Status: Downloaded newer image for obolibrary/odkfull:latest
hp.Makefile:72: warning: overriding recipe for target 'test'
Makefile:46: warning: ignoring old recipe for target 'test'
hp.Makefile:76: warning: overriding recipe for target 'hp.owl'
Makefile:169: warning: ignoring old recipe for target 'hp.owl'
touch  ../patterns/data/default/abnormalAnatomicalEntity.txt  ../patterns/data/default/atreticAnatomicalEntity.txt  ../patterns/data/default/abnormalBiologicalProcessInLocation.txt  ../patterns/data/default/atrophiedAnatomicalStructure.txt  ../patterns/data/default/abnormalConcentrationOfChemicalEntityInLocation.txt   &&\
  touch  ../patterns/data/default/abnormalAnatomicalEntity.ofn  ../patterns/data/default/atreticAnatomicalEntity.ofn  ../patterns/data/default/abnormalBiologicalProcessInLocation.ofn  ../patterns/data/default/atrophiedAnatomicalStructure.ofn  ../patterns/data/default/abnormalConcentrationOfChemicalEntityInLocation.ofn  
dosdp-tools terms --infile=../patterns/data/default/abnormalAnatomicalEntity.tsv --template=../patterns/dosdp-patterns/abnormalAnatomicalEntity.yaml --obo-prefixes=true --outfile=../patterns/data/default/abnormalAnatomicalEntity.txt
dosdp-tools terms --infile=../patterns/data/default/atreticAnatomicalEntity.tsv --template=../patterns/dosdp-patterns/atreticAnatomicalEntity.yaml --obo-prefixes=true --outfile=../patterns/data/default/atreticAnatomicalEntity.txt
dosdp-tools terms --infile=../patterns/data/default/abnormalBiologicalProcessInLocation.tsv --template=../patterns/dosdp-patterns/abnormalBiologicalProcessInLocation.yaml --obo-prefixes=true --outfile=../patterns/data/default/abnormalBiologicalProcessInLocation.txt
dosdp-tools terms --infile=../patterns/data/default/atrophiedAnatomicalStructure.tsv --template=../patterns/dosdp-patterns/atrophiedAnatomicalStructure.yaml --obo-prefixes=true --outfile=../patterns/data/default/atrophiedAnatomicalStructure.txt
dosdp-tools terms --infile=../patterns/data/default/abnormalConcentrationOfChemicalEntityInLocation.tsv --template=../patterns/dosdp-patterns/abnormalConcentrationOfChemicalEntityInLocation.yaml --obo-prefixes=true --outfile=../patterns/data/default/abnormalConcentrationOfChemicalEntityInLocation.txt
cat ../patterns/dosdp-patterns/external.txt | sed 's!.*/!!' | sed 's! !!g' |  xargs -I{} rm -f ../patterns/dosdp-patterns/{}
cat ../patterns/dosdp-patterns/external.txt | sed 's! !!g' | xargs -I{} wget -q {} -P ../patterns/dosdp-patterns
simple_pattern_tester.py ../patterns/dosdp-patterns/ # 2>&1 | tee pattern_schema_checks
/tools//simple_pattern_tester.py:96: UserWarning: Checking ../patterns/dosdp-patterns/abnormalAnatomicalEntity.yaml
  warnings.warn("Checking %s" % pattern_doc)
/tools//simple_pattern_tester.py:96: UserWarning: Checking ../patterns/dosdp-patterns/abnormalBiologicalProcessInLocation.yaml
  warnings.warn("Checking %s" % pattern_doc)
/tools//simple_pattern_tester.py:96: UserWarning: Checking ../patterns/dosdp-patterns/abnormalConcentrationOfChemicalEntity.yaml
  warnings.warn("Checking %s" % pattern_doc)
/tools//simple_pattern_tester.py:96: UserWarning: Checking ../patterns/dosdp-patterns/abnormalConcentrationOfChemicalEntityInLocation.yaml
  warnings.warn("Checking %s" % pattern_doc)
/tools//simple_pattern_tester.py:96: UserWarning: Checking ../patterns/dosdp-patterns/abnormalDegenerationOfAnatomicalEntity.yaml
  warnings.warn("Checking %s" % pattern_doc)
/tools//simple_pattern_tester.py:96: UserWarning: Checking ../patterns/dosdp-patterns/atreticAnatomicalEntity.yaml
  warnings.warn("Checking %s" % pattern_doc)
/tools//simple_pattern_tester.py:96: UserWarning: Checking ../patterns/dosdp-patterns/atrophiedAnatomicalEntity.yaml
  warnings.warn("Checking %s" % pattern_doc)
/tools//simple_pattern_tester.py:96: UserWarning: Checking ../patterns/dosdp-patterns/atrophiedAnatomicalStructure.yaml
  warnings.warn("Checking %s" % pattern_doc)
/tools//simple_pattern_tester.py:96: UserWarning: Checking ../patterns/dosdp-patterns/degenerationOfAnatomicalEntity.yaml
  warnings.warn("Checking %s" % pattern_doc)
dosdp-tools prototype --obo-prefixes --template=../patterns/dosdp-patterns --outfile=../patterns/pattern.owl
Row: Map(biological_process -> 'biological process', location -> 'anatomical entity', defined_class -> http://purl.obolibrary.org/obo/upheno/patterns-dev/abnormalBiologicalProcessInLocation.yaml)
Row: Map(anatomical_entity -> 'anatomical entity', defined_class -> http://purl.obolibrary.org/obo/upheno/patterns/abnormalAnatomicalEntity.yaml)
Row: Map(chemical -> chemical, defined_class -> http://purl.obolibrary.org/obo/upheno/patterns-dev/abnormalConcentrationOfChemicalEntity.yaml)
Row: Map(anatomical_entity -> 'anatomical entity', defined_class -> http://purl.obolibrary.org/obo/upheno/patterns-dev/abnormalDegenerationOfAnatomicalEntity.yaml)
Row: Map(anatomical_entity -> 'anatomical entity', defined_class -> http://purl.obolibrary.org/obo/upheno/patterns-dev/atreticAnatomicalEntity)
Row: Map(anatomical_entity -> 'anatomical entity', defined_class -> http://purl.obolibrary.org/obo/upheno/patterns-dev/atrophiedAnatomicalEntity.yaml)
Row: Map(anatomical_entity -> 'anatomical entity', defined_class -> http://purl.obolibrary.org/obo/upheno/patterns-dev/degenerationOfAnatomicalEntity.yaml)
Row: Map(chemical -> chemical, location -> 'anatomical entity', defined_class -> http://purl.obolibrary.org/obo/upheno/patterns-dev/abnormalConcentrationOfChemicalEntityInLocation.yaml)
Row: Map(entity -> 'entity', defined_class -> http://purl.obolibrary.org/obo/upheno/patterns/atrophiedAnatomicalStructure)
cat ../patterns/data/default/abnormalAnatomicalEntity.txt ../patterns/data/default/atreticAnatomicalEntity.txt ../patterns/data/default/abnormalBiologicalProcessInLocation.txt ../patterns/data/default/atrophiedAnatomicalStructure.txt ../patterns/data/default/abnormalConcentrationOfChemicalEntityInLocation.txt ../patterns/pattern_owl_seed.txt | sort | uniq > ../patterns/all_pattern_terms.txt
Killed
make: *** [Makefile:239: seed.txt] Error 137
```

**Comment by matentzn** [comment]
This error is most likely caused by a lack of memory.

Docker -> Preferences -> Advanced -> [Increase memory to 6GB or 8GB]

Does this work?

**Comment by kingmanzhang** [comment]
Yes, it worked. It took a while to finish the process (> 10 min).  There seems some errors in inference and reports, but I got what I want.

Last few lines:
```
robot report -i hp-edit.owl --fail-on ERROR -o reports/hp-edit-obo-report.tsv
Violations: 24548
-----------------
ERROR:      224
WARN:       24314
INFO:       10
2019-05-03 15:35:53,951 ERROR org.obolibrary.robot.ReportCommand - Report failed!
make: *** [Makefile:408: reports/hp-edit-obo-report.tsv] Error 1
rm imports/pato_terms_combined.txt imports/mpath_terms_combined.txt imports/hsapdv_terms_combined.txt imports/cl_terms_combined.txt
```

**Comment by kingmanzhang** [comment]
I am closing for now.

**Comment by matentzn** [comment]
Whoops you incidentally found a tripwire for sebastians next release generation :P I fixed it. git pull and run again.

You can now bypass the import resolution (which is about 2/3s of the overall build time) like this:

```
sh run.sh make IMP=false prepare_release
```

Good luck!

**Comment by kingmanzhang** [comment]
Thanks @matentzn for your help !

If possible, I would suggest creating an easier way for non-expert users like me to build local HPO, such as by putting
```
sh run.sh make IMP=false prepare_release
```
into a new executable script named such as "build_local_hpo" so that I can just run without thinking about what the commands and variables mean. I do not think ordinary users would understand them, but they may have the need to build a local version to use most up-to-date hpo.

**Comment by matentzn** [comment]
I will do this right now. Good call.

**Comment by matentzn** [comment]
https://github.com/obophenotype/human-phenotype-ontology/blob/master/src/ontology/build-without-imports.sh

Dont know though where this should be documented..

**Comment by kingmanzhang** [comment]
Great! Maybe open a section in "Readme.me"?
